### ISSUE TITLE
mybot down?

### ISSUE THREAD

**Issue by ryukai888** [NguyenAnhHD/MyBot.Run-AIO-MOD#3]
Hello Sir,

I've been mybot users for years and years.....never seen this coming.

what's going on with mybot?

I cannot open the website nor authenticate my login for the bot to run.

please shed some lights for me...thanks for all of your hard work on the mod...your mod is the best Sir

**Comment by NguyenAnhHD** [comment]
This issue, please ask Admin of the forum.  I do not know the information as well as the rights on the forum.

**Comment by ryukai888** [comment]
cannot even access the website to start with.
by any chance you know the rocket chat server link name?
I'll try my luck on that chat

**Comment by RockyMountainHigh** [comment]
I can't access the forum also. :( If it's still down in the morning I'll take a look at removing the authentication when I have some time.

Is there a relatively easy way to do it? I have done some autoit work before.

**Comment by ryukai888** [comment]
@RockyMountainHigh ...that will be awesome to be able to bypass the authentication so the bot can run without it....pls keep us posted

**Comment by RockyMountainHigh** [comment]
I've done no work on MyBot.run to this point so hopefully they get the forum back up. I can't even tell if its a money thing or something.

**Comment by RockyMountainHigh** [comment]
I'm not a contributor here, but here is a quick work around if you can figure out how to compile.

Download the source code. Make sure you have autoit installed

1) In file MyBot.run.au3, comment out line 606
2) In file 'MBR GUI Action.au3 comment out lines 90-93
3) Recompile MyBot.run.au3

At that point you will have a new .exe in the directory that will work and not try to authenticate forum.

Obviously use at your own risk

Nguyen, you aware of any issues with doing this?

**Comment by RockyMountainHigh** [comment]
Appears that the forum is back up now.

**Comment by ryukai888** [comment]
Yes, it seems they got it up and running. Just ran mybot and it pass the authentication steps smoothly. Thanks for the help @RockyMountainHigh
